default: &default
  adapter: postgresql
  host: localhost
  username: justask
  password: password

development:
  <<: *default
  database: justask_dev

test:
  <<: *default
  database: justask_test

staging:
  <<: *defaults
  database: justmet_staging

production:
  <<: *default
  database: justask_prod
